---
- name: Install Bash
  pacman:
    name: ["bash", "bash-completion"]
    state: present
  tags:
    - shell

- name: Install ZSH
  pacman:
    name: ["zsh", "zsh-completions"]
    state: present
  tags:
    - shell

- name: Clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/{{ user.name }}/.oh-my-zsh

- name: deploy .zshrc
  template: src=files/zshrc.j2 dest=/home/{{ user.name }}/.zshrc owner={{ user.name }}

# - name: remove standard zshrc
#   file: path=/home/{{ user.name }}/.zshrc state=absent

# - name: Create conf folder in home directory
#   file: path=/home/{{ user.name }}/conf/ state=directory owner={{ user.name }}

# - name: symlink zshrc
#   file: path=/home/{{ user.name }}/.zshrc src=/home/{{ user.name }}/conf/zshrc state=link owner={{ user.name }}

- name: Set zsh as default shell
  user: name={{ user.name }} shell=/bin/zsh
